
# Generated by Django 5.1.1 on 2024-10-26 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('interests', models.TextField()),
                ('branche', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportantInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QuizAbsolved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField()),
                ('AnswerFromUser', models.TextField(blank=True)),
                ('AiAnswer', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ImportantInformations', models.ManyToManyField(blank=True, to='app.importantinformation')),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_why', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('reported_type', models.CharField(choices=[('thread', 'Thread'), ('comment', 'Comment'), ('question', 'SharedQuestion')], max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequests',
            fields=[
                ('search_id', models.AutoField(primary_key=True, serialize=False)),
                ('search_term', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('search_result', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id_thread', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.TextField()),
                ('content', models.TextField()),
                ('content_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('main_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_threads', to='app.tag')),
                ('subtags', models.ManyToManyField(blank=True, related_name='sub_threads', to='app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='SolvedThreads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('QuizAbsolved', models.ManyToManyField(blank=True, to='app.quizabsolved')),
                ('Threads', models.ManyToManyField(blank=True, to='app.thread')),
            ],
        ),
        migrations.CreateModel(
            name='SharedQuestion',
            fields=[
                ('shared_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_questions', to='app.thread')),
            ],
        ),
        migrations.AddField(
            model_name='importantinformation',
            name='informationFrom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.thread'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reacting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app.comment')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.thread')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='image_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.uploadedimage'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downvotedComments', models.ManyToManyField(related_name='downvotedComments', to='app.comment')),
                ('downvotedSharedQuestions', models.ManyToManyField(related_name='downvotedSharedQuestions', to='app.sharedquestion')),
                ('downvotedThreads', models.ManyToManyField(related_name='threadsDownvoted', to='app.thread')),
                ('upvotedComments', models.ManyToManyField(related_name='upvotedComments', to='app.comment')),
                ('upvotedSharedQuestions', models.ManyToManyField(related_name='upvotedSharedQuestions', to='app.sharedquestion')),
                ('upvotedThreads', models.ManyToManyField(related_name='threadsUpvoted', to='app.thread')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.uploadedimage')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.job')),
                ('solvedThreads', models.ManyToManyField(blank=True, to='app.solvedthreads')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
