# Generated by Django 5.1.1 on 2024-10-26 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['comment_id']},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='importantinformation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='reportmodel',
            options={'ordering': ['report_id']},
        ),
        migrations.AlterModelOptions(
            name='searchrequests',
            options={'ordering': ['search_id']},
        ),
        migrations.AlterModelOptions(
            name='sharedquestion',
            options={'ordering': ['shared_id']},
        ),
        migrations.AlterModelOptions(
            name='solvedthreads',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['id_thread']},
        ),
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ['image_id']},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userpreferences',
            options={'ordering': ['id']},
        ),
    ]
