# Generated by Django 5.1.1 on 2024-10-27 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_comment_options_alter_companyprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.uploadedimage'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='solvedThreads',
            field=models.ManyToManyField(blank=True, null=True, to='app.solvedthreads'),
        ),
    ]
